/*
 * generated by Xtext 2.20.0
 */
package org.iot.codegenerator.tests

import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.junit.jupiter.api.^extension.ExtendWith

@ExtendWith(InjectionExtension)
@InjectWith(CodeGeneratorInjectorProvider)
class CodeGeneratorParsingTest {

}
