/*
 * generated by Xtext 2.20.0
 */
package org.iot.codegenerator


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class CodeGeneratorStandaloneSetup extends CodeGeneratorStandaloneSetupGenerated {

	def static void doSetup() {
		new CodeGeneratorStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
